config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about', to: 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }

  resources :users, only: [:edit, :update, :destroy, :show] do
    collection do
      get 'mypage', to: 'users#mypage'
      get 'search', to: 'users#search'
    end
    member do
      get 'liked_posts', to: 'users#liked_posts'
    end
  end

  post 'users/guest_sign_in', to: 'users#guest_sign_in'

  resources :posts do
    collection do
      get 'search', to: 'posts#search'
    end
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :groups do
    member do
      post 'join'
      delete 'leave'
    end
    resources :user_groups, only: [:create, :destroy]
  end

  namespace :admin do
    resources :groups
    resources :users, except: [:new, :create]
    resources :posts, except: [:new, :create]
    resources :comments, except: [:new, :create]
  end

  get 'search', to: 'search#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/models/admin_user.rb
# app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  # Associations
  belongs_to :owner, class_name: 'User', foreign_key: 'new_owner_id', optional: false
  has_one_attached :image
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :posts, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :description, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Validations
  validates :title, presence: true
  validates :content, presence: true
  validate :group_presence_if_id_present

  private

  def group_presence_if_id_present
    if group_id.present? && group.nil?
      errors.add(:group, "must exist")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_one_attached :profile_image
  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :owned_groups, class_name: 'Group', foreign_key: 'new_owner_id', dependent: :destroy
  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  # Check if the user has liked a specific post
  def like(post)
    self.likes.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    self.likes.find_by(post_id: post.id)&.destroy
  end

  def liked?(post)
    likes.exists?(post_id: post.id)
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'admin'

  def index
    @comments = Comment.all
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path, notice: 'コメントが削除されました。'
  end
end

app/controllers/admin_user/comments_controller.rb
# app/controllers/admin_user/comments_controller.rb
class AdminUser::CommentsController < ApplicationController
  layout 'admin'

  def index
    @comments = Comment.all
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path, notice: 'コメントが削除されました。' 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by_id(params[:id])
    @comment.destroy if @comment
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
   @groups = Group.order(created_at: :desc).page(params[:page]).per(6)
    @recent_posts = Post.where(group_id: nil).order(created_at: :desc).page(params[:page]).per(6)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    current_user.like(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    current_user.unlike(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_like]
  before_action :set_group, only: [:new, :create, :edit, :update]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(8)
    else
      @posts = current_user.posts.order(created_at: :desc).page(params[:page]).per(8)
    end
  end
  
  def show
  end

  def new
    @post = @group ? @group.posts.build : Post.new
  end

  def create
    @post = @group ? @group.posts.build(post_params) : Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @group ? group_path(@group) : post_path(@post), notice: '投稿が作成されました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      if @group
        redirect_to group_path(@group), notice: '投稿が更新されました。'
      else
        redirect_to post_path(@post), notice: '投稿が更新されました。'
      end
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: '投稿が削除されました。'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id]) if params[:group_id].present?
  rescue ActiveRecord::RecordNotFound
    @group = nil
    redirect_to groups_path, alert: 'グループが見つかりません。' if params[:group_id].present?
  end

  def post_params
    params.require(:post).permit(:title, :content, :group_id, images: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :show, :update, :destroy, :liked_posts]

  def mypage
    @user = current_user
    @posts = @user.posts.page(params[:page])
  end
  
  def edit
  end

  def show
    @posts = @user.posts.order(created_at: :desc).limit(3)
  end

  def update
    if @user.update(user_params)
      redirect_to mypage_users_path, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'ユーザーが削除されました'
  end

  def liked_posts
    @liked_posts = @user.liked_posts.page(params[:page])
  end

  def search
  end

  def search_results
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
    unless @user
      redirect_to root_path, alert: "ユーザーが見つかりませんでした。"
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/comments/edit.html.erb
<h1>Admin::Comments#edit</h1>
<p>Find me in app/views/admin/comments/edit.html.erb</p>

app/views/admin/comments/index.html.erb
<!-- app/views/admin/comments/index.html.erb -->
<h1 class="mt-4">コメント管理</h1>
<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>ユーザー名</th>
      <th>内容</th>
      <th>作成日時</th>
      <th>投稿</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user ? comment.user.name : 'ユーザーなし' %></td>
        <td><%= comment.content %></td>
        <td><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= link_to'元の投稿を見る', post_path(comment.post) %></td>
        <td>
          <%= link_to '削除', admin_comment_path(comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/comments/show.html.erb
<h1>Admin::Comments#show</h1>
<p>Find me in app/views/admin/comments/show.html.erb</p>

app/views/admin/comments/update.html.erb
<h1>Admin::Comments#update</h1>
<p>Find me in app/views/admin/comments/update.html.erb</p>

app/views/comments/_comment.html.erb
<div id="comment__<%= comment.id %>" class="d-flex justify-content-between align-items-center">
  <p class="mb-1"><strong><%= comment.user.name %>:</strong> <%= comment.content %></p>
  <% if current_user && comment.user == current_user %>
    <%= link_to '削除', post_comment_path(comment.post, comment), remote: true, method: :delete, class: 'btn btn-danger btn-sm ml-2' %>
  <% end %>
</div>

app/views/comments/_comment_form.html.erb
<% if current_user %>
  <%= form_with(model: [post, Comment.new], local: false) do |form| %>
    <div class="form-group">
      <%= form.label :content, "コメントを追加" %>
      <%= form.text_area :content, rows: 3, class: "form-control", id: 'comment-form' %>
    </div>
    <%= form.submit "コメントする", class: "btn btn-primary" %>
  <% end %>
<% else %>
  <p>コメントを追加するにはログインしてください。</p>
  <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.js.erb
$("#comments").prepend('<%=j render 'comments/comment', comment: @comment %>');
$("#comment-form").val("");
$("#comment-count").text('<%= @comment.post.comments.size %>');

app/views/comments/destroy.js.erb
$("#comment__<%= @comment.id %>").remove();
$("#comment-count").text('<%= @comment.post.comments.size %>');