config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about', to: 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }

  resources :users, only: [:edit, :update, :destroy, :show] do
    collection do
      get 'mypage', to: 'users#mypage'
      get 'search', to: 'users#search'
    end
    member do
      get 'liked_posts', to: 'users#liked_posts'
    end
  end

  post 'users/guest_sign_in', to: 'users#guest_sign_in'

  resources :posts do
    collection do
      get 'search', to: 'posts#search'
    end
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :groups do
    member do
      post 'join'
      delete 'leave'
    end
    resources :user_groups, only: [:create, :destroy]
  end

  namespace :admin do
    resources :groups
    resources :users, except: [:new, :create]
    resources :posts, except: [:new, :create]
    resources :comments, except: [:new, :create]
  end

  get 'search', to: 'search#index'
end

app/models/group.rb
class Group < ApplicationRecord
  # Associations
  belongs_to :owner, class_name: 'User', foreign_key: 'new_owner_id', optional: false
  has_one_attached :image
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :posts, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to admin_group_path(@group), notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to admin_group_path(@group), notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to admin_groups_path, notice: 'グループが削除されました'
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :image)
  end
end

app/controllers/admin_user/groups_controller.rb
# app/controllers/admin_user/groups_controller.rb
class AdminUser::GroupsController < ApplicationController
  layout 'admin'

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to admin_user_group_path(@group), notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to admin_user_group_path(@group), notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to admin_user_groups_path, notice: 'Group was successfully destroyed.'
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join, :leave]
  before_action :ensure_owner_or_admin, only: [:edit, :update, :destroy]
  before_action :ensure_admin, only: [:manage]

  def index
    @groups = Group.all
  end

  def show
    if user_signed_in?
      @is_owner = current_user == @group.owner
      @is_member = @group.users.exists?(current_user.id)
    else
      @is_owner = false
      @is_member = false
    end
    @group_posts = @group.posts.order(created_at: :desc).page(params[:page])
  end

  def new
    @group = current_user.owned_groups.build
  end

  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    if @group.save
      redirect_to @group, notice: 'グループが作成されました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'グループが更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to root_path, notice: 'グループが削除されました。'
  end

  def join
    unless @group.users.include?(current_user)
      @group.user_groups.create(user: current_user, joined_at: Time.current)
      redirect_to @group, notice: 'グループに参加しました。'
    end
  end

  def leave
    if @group.users.include?(current_user)
      @group.users.delete(current_user)
      redirect_to @group, notice: 'グループから外れました。'
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def ensure_owner_or_admin
    unless @group.owner == current_user || current_user.admin?
      redirect_to groups_path, alert: 'グループを編集する権限がありません。'
    end
  end

  def ensure_admin
    unless current_user.admin?
      redirect_to root_path, alert: '管理者権限が必要です。'
    end
  end

  def group_params
    params.require(:group).permit(:name, :description, :image)
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, local: true) do |form| %>
  <!-- その他のフィールド -->
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= form.submit '保存', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/_group_actions.html.erb
<!--group_action-->
<% if is_owner %>
  <%= link_to 'グループ編集', edit_group_path(group), class: 'btn btn-primary btn-block btn-sm mt-3 btn-custom' %>
<% end %>
<% if is_member %>
  <%= link_to 'グループ退会', leave_group_path(group), method: :delete, class: 'btn btn-danger btn-block btn-sm mt-3 btn-custom', data: { confirm: '本当に退会しますか？' } %>
<% end %>

app/views/groups/_group_image.html.erb
<!--group_image-->
<% if group.image.attached? %>
  <%= image_tag url_for(group.image), class: 'img-fluid mb-3' %>
<% end %>

app/views/groups/_group_post_actions.html.erb
<!--group_post_actions-->
<% if is_member %>
  <%= link_to '投稿する', new_post_path(group_id: group.id), class: 'btn btn-success btn-sm btn-custom mb-3' %>
<% else %>
  <%= form_with url: join_group_path(group), method: :post do %>
    <%= submit_tag 'このグループに参加', class: 'btn btn-primary btn-sm btn-custom mb-3' %>
  <% end %>
<% end %>

app/views/groups/_post_card.html.erb
<!--groups/post_card-->
<div class="col-md-4">
  <div class="card mt-3" style="max-width: 300px;">
    <div class="row no-gutters">
      <% if post.images.attached? %>
        <div class="col-md-4">
          <%= image_tag url_for(post.images.first), class: 'img-fluid', alt: '投稿画像', style: 'width: 100px; height: 70px; object-fit: cover;' %>
        </div>
      <% end %>
      <div class="col-md-8">
        <div class="card-body">
          <p class="mb-1" style="font-size: 0.8em;">
            <strong><%= post.user.name %></strong>
            <span class="text-muted" style="font-size: 0.7em;"><%= post.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M") %></span>
          </p>
          <h5 class="card-title" style="font-size: 1em;">
            <%= link_to truncate(post.title, length: 8), post_path(post), class: 'text-decoration-none' %>
          </h5>
          <p class="card-text" style="font-size: 0.8em;"><%= truncate(post.content, length: 8) %></p>
          <div class="d-flex align-items-center">
            <i class="fas fa-users mr-1"></i>
            <span class="mr-2"><%= truncate(post.group.name, length: 4) %></span>
            <i class="fas fa-heart mr-1"></i>
            <span class="mr-2"><%= post.likes.count %></span>
            <i class="fas fa-comment mr-1"></i>
            <span><%= post.comments.count %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card" style="background-color: #FFFAF0;">
        <div class="card-body">
          <h3 class="display-6 my-4" style="font-family: 'Dancing Script', cursive; color: #5a5a5a;">グループ編集</h3>

          <%= form_with(model: @group, local: true) do |form| %>
            <% if @group.image.attached? %>
              <div class="form-group">
                <div class="row">
                  <div class="col-md-6 mb-2">
                    <%= image_tag @group.image, class: 'img-fluid', alt: 'グループ画像' %>
                  </div>
                </div>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.label :image, "グループ画像", for: 'group_image' %>
              <%= form.file_field :image, id: 'group_image', class: 'form-control' %>
            </div>
            
            <div class="form-group">
              <%= form.label :name, "グループ名", for: 'group_name' %>
              <%= form.text_field :name, id: 'group_name', class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :description, "説明", for: 'group_description' %>
              <%= form.text_area :description, id: 'group_description', class: 'form-control', rows: 5 %>
            </div>

            <div class="d-flex">
              <%= form.submit '更新', class: 'btn btn-primary mr-2' %>
              <%= link_to 'グループ削除', group_path(@group), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<!-- app/views/groups/index.html.erb -->
<h1>グループ一覧</h1>
<%= link_to 'グループ作成', new_group_path, class: 'btn btn-primary' %>
<ul>
  <% @groups.each do |group| %>
    <li>
      <%= link_to group.name, group_path(group) %>
      (メンバー: <%= group.users.count %>)
      <% if group.owner == current_user %>
        <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-secondary' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<h1 class="text-center">新規グループ作成</h1> 

<div class="container mt-5" style="max-width: 600px;">
  <%= form_with(model: @group, local: true, html: { multipart: true }) do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
        <ul>
          <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :image, "グループ画像" %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :name, "グループ名" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "説明" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    

    <div class="form-group text-center">
      <%= f.submit "作成", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<style>
  .form-container {
    max-width: 600px;
    margin: 0 auto;
  }
  .form-container h1 {
    margin-bottom: 30px;
  }
  .form-container .form-group {
    margin-bottom: 15px;
  }
  .form-container .btn-primary {
    width: 100px;
  }
</style>

app/views/groups/show.html.erb
<div class="container main-content"> 
  <div class="row">
    <div class="col-md-3">
      <%= render 'group_image', group: @group %>
      <div class="list-group mt-3">
        <h4>グループメンバー (<%= @group.users.count %>)</h4>
        <% @group.users.each do |user| %>
          <%= link_to user.name, user_path(user), class: 'list-group-item list-group-item-action' %>
        <% end %>
      </div>
      <%= render 'group_actions', group: @group, is_owner: @is_owner, is_member: @is_member %>
    </div>

    <div class="col-md-9">
      <p class="text-muted"><%= @group.created_at.strftime("%Y-%m-%d %H:%M") %></p> <!-- グループ作成日時の表示 -->
      <h2><%= @group.name %></h2>
      <p><%= @group.description %></p>
      <%= render 'group_post_actions', group: @group, is_member: @is_member %>
      <div class="row">
        <% @group_posts.each do |post| %>
          <%= render 'post_card', post: post %>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <%= paginate @group_posts %>
      </div>
    </div>
  </div>
</div>

<style>
  .btn-custom {
    width: auto;
    display: inline-block;
  }
  .card {
    margin-bottom: 10px;
  }
  .card-body {
    padding: 10px;
  }
  .card-title a {
    color: #5a5a5a;
  }
  .card-title a:hover {
    color: #ff6347;
  }
  .img-thumbnail {
    border: none;
    padding: 0;
  }
</style>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>