config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about', to: 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }

  resources :users, only: [:edit, :update, :destroy, :show] do
    collection do
      get 'mypage', to: 'users#mypage'
      get 'search', to: 'users#search'
    end
    member do
      get 'liked_posts', to: 'users#liked_posts'
    end
  end

  post 'users/guest_sign_in', to: 'users#guest_sign_in'

  resources :posts do
    collection do
      get 'search', to: 'posts#search'
    end
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :groups do
    member do
      post 'join'
      delete 'leave'
    end
    resources :user_groups, only: [:create, :destroy]
  end

  namespace :admin do
    resources :groups
    resources :users, except: [:new, :create]
    resources :posts, except: [:new, :create]
    resources :comments, except: [:new, :create]
  end

  get 'search', to: 'search#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # Validations
  validates :title, presence: true
  validates :content, presence: true
  validate :group_presence_if_id_present

  private

  def group_presence_if_id_present
    if group_id.present? && group.nil?
      errors.add(:group, "must exist")
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_user_post_path(@post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_user_post_path(@post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_user_posts_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/admin_user/posts_controller.rb
# app/controllers/admin_user/posts_controller.rb
class AdminUser::PostsController < ApplicationController
  layout 'admin'

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_user_post_path(@post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_user_post_path(@post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_user_posts_path, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_like]
  before_action :set_group, only: [:new, :create, :edit, :update]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(8)
    else
      @posts = current_user.posts.order(created_at: :desc).page(params[:page]).per(8)
    end
  end
  
  def show
  end

  def new
    @post = @group ? @group.posts.build : Post.new
  end

  def create
    @post = @group ? @group.posts.build(post_params) : Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @group ? group_path(@group) : post_path(@post), notice: '投稿が作成されました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      if @group
        redirect_to group_path(@group), notice: '投稿が更新されました。'
      else
        redirect_to post_path(@post), notice: '投稿が更新されました。'
      end
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: '投稿が削除されました。'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id]) if params[:group_id].present?
  rescue ActiveRecord::RecordNotFound
    @group = nil
    redirect_to groups_path, alert: 'グループが見つかりません。' if params[:group_id].present?
  end

  def post_params
    params.require(:post).permit(:title, :content, :group_id, images: [])
  end
end

app/controllers/users/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: '投稿が作成されました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: '投稿が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: '投稿が削除されました。'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :keywords)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "権限がありません" if @post.nil?
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_favorites.html.erb
<div id="favorite-<%= post.id %>">
  <% if current_user.liked?(post) %>
    <%= link_to post_toggle_like_path(post), method: :post, remote: true, id: "like-link-#{post.id}" do %>
      <i class="fas fa-heart" id="like-icon-<%= post.id %>" style="cursor: pointer; color: red;"></i>
    <% end %>
  <% else %>
    <%= link_to post_toggle_like_path(post), method: :post, remote: true, id: "like-link-#{post.id}" do %>
      <i class="fas fa-heart" id="like-icon-<%= post.id %>" style="cursor: pointer; color: black;"></i>
    <% end %>
  <% end %>
  <span id="likes-count-<%= post.id %>"><%= post.likes.count %></span>
</div>

app/views/posts/_form.html.erb
<!-- app/views/posts/_form.html.erb -->
<%= form_with(model: @post, local: true) do |form| %>
  <!-- その他のフィールド -->
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= form.submit '保存', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_group_info.html.erb
<% if post.group %>
  <div class="mt-3">
    <i class="fas fa-users mr-1"></i>
    <span class="mr-2"><%= link_to truncate(post.group.name, length: 12), group_path(post.group) %></span>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card mt-3">
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <p class="card-text"><%= truncate(post.content, length: 100) %></p>
    <%= link_to '詳細を見る', post_path(post), class: 'btn btn-primary' %>
  </div>
</div>

app/views/posts/_user_profile.html.erb
<div class="position-absolute d-flex align-items-center" style="top: 10px; left: 10px; padding-bottom: 5px;">
  <%= link_to user_path(user), class: 'd-flex align-items-center', style: 'text-decoration: none;' do %>
    <% if user.profile_image.attached? %>
      <%= image_tag user.profile_image.variant(resize: "50x50").processed, size: "50x50", class: 'rounded-circle', alt: 'プロフィール画像' %>
    <% else %>
      <%= image_tag 'default_profile.png', size: "50x50", class: 'rounded-circle', alt: 'デフォルトプロフィール画像' %>
    <% end %>
    <span class="ml-2" style="color: #5a5a5a;"><%= user.name %></span>
  <% end %>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card" style="background-color: #FFFAF0;">
        <div class="card-body">
          <h3 class="display-6 my-4" style="font-family: 'Dancing Script', cursive; color: #5a5a5a;">編集ページ</h3>

          <%= form_with(model: @post, local: true, html: { multipart: true }) do |form| %>
            <% if @post.images.attached? %>
              <div class="form-group">
                <div class="row">
                  <% @post.images.each do |image| %>
                    <div class="col-md-6 mb-2">
                      <%= image_tag image, class: 'img-fluid', alt: '投稿画像' %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
            
            <div class="form-group">
              <%= form.label :images, "画像", for: 'post_images', class: 'form-label' %>
              <%= form.file_field :images, id: 'post_images', multiple: true, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :content, "内容" %>
              <%= form.text_area :content, class: 'form-control', rows: 5 %>
            </div>

            <div class="d-flex">
              <%= form.submit '更新', class: 'btn btn-primary mr-2' %>
              <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h3 class="display-6 my-4" style="font-family: #5a5a5a;">
  <%= @user ? "#{@user.name}さんの投稿一覧" : "あなたの投稿一覧" %>
</h3>
<div class="row">
  <% if @posts.present? %>
    <% @posts.each_slice(4) do |post_group| %>
      <% post_group.each do |post| %>
        <div class="col-sm-3 mb-4">
          <div class="card post p-3 border rounded content-box">
            <div class="d-flex align-items-center mb-2">
              <%= render partial: 'layouts/profile_image', locals: { user: post.user } %>
              <div class="ml-2">
                <p class="text-muted mb-0" style="font-size: 0.8em;"><%= post.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H:%M") %></p>
              </div>
            </div>
            <% if post.images.attached? %>
              <div class="mb-2">
                <%= image_tag post.images.first, class: 'img-fluid', style: 'width: 100%; height: 150px; object-fit: cover;', alt: '投稿画像' %>
              </div>
            <% else %>
              <div class="mb-2">
                <%= image_tag 'default_image.jpg', class: 'img-fluid', style: 'width: 100%; height: 150px; object-fit: cover;', alt: 'デフォルト画像' %>
              </div>
            <% end %>
            <div>
              <h5 class="font-italic post-title mb-1" style="font-size: 1em;">
                <%= link_to truncate(post.title, length: 10), post, class: 'text-decoration-none' %>
              </h5>
              <p class="post-content" style="font-size: 0.9em;">
                <%= truncate(post.content, length: 10) %>
              </p>
            </div>
            <div class="d-flex justify-content-start align-items-center mt-3">
              <div class="d-flex align-items-center mr-3">
                <i class="fas fa-heart"></i>
                <p class="text-muted mb-0 ml-1"><%= post.likes.count %></p>
              </div>
              <div class="d-flex align-items-center mr-3">
                <i class="fas fa-comment"></i>
                <p class="text-muted mb-0 ml-1"><%= post.comments.count %></p>
              </div>
              <% if post.group.present? %>
                <div class="d-flex align-items-center">
                  <i class="fas fa-users fa-sm mr-1"></i>
                  <p class="text-muted mb-0"><%= truncate(post.group.name, length: 5) %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="col-12 text-center">
      <p>投稿がありません。</p>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <%= paginate @posts %>
</div>

<style>
  .content-box {
    background-color: #FFFAF0;
    padding: 10px;
    margin-bottom: 15px;
    border-radius: 5px;
    border: 1px solid #ddd;
  }

  .post-title a {
    color: #5a5a5a;
  }

  .post-title a:hover {
    color: #ff6347;
  }

  .post-content {
    margin-bottom: 10px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card border-0">
        <div class="card-body">
          <% if user_signed_in? %>
            <%= form_with(model: @post, local: true, html: { multipart: true }) do |form| %>
              <% if @post.errors.any? %>
                <div id="error_explanation" class="alert alert-danger">
                  <ul>
                    <% @post.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <% if @group %>
                <%= form.hidden_field :group_id, value: @group.id %>
              <% end %>

              <div class="form-group">
                <%= form.label :images, "画像", for: 'post_images', class: 'form-label' %>
                <%= form.file_field :images, id: 'post_images', multiple: true, class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= form.label :title, "タイトル", for: 'post_title', class: 'form-label' %>
                <%= form.text_field :title, id: 'post_title', class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= form.label :content, "内容", for: 'post_content', class: 'form-label' %>
                <%= form.text_area :content, id: 'post_content', class: 'form-control', rows: 5 %>
              </div>

              <div class="text-center">
                <%= form.submit "投稿", class: 'btn btn-primary' %>
              </div>
            <% end %>
          <% else %>
            <div class="text-center">
              <p>投稿するにはログインが必要です。</p>
              <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .form-label {
    font-weight: bold;
    color: #495057;
  }

  .form-control {
    margin-bottom: 15px;
  }

  .btn-primary {
    background-color: #007bff;
    border-color: #007bff;
  }
</style>

app/views/posts/search.html.erb
<h1>投稿検索</h1>
<%= form_tag search_results_posts_path, method: :get do %>
  <div class="form-group">
    <%= label_tag :q, 'キーワード' %>
    <%= text_field_tag :q, params[:q], class: 'form-control' %>
  </div>
  <%= submit_tag '検索', class: 'btn btn-primary' %>
<% end %>

app/views/posts/search_results.html.erb
<h1>検索結果</h1>
<% @posts.each do |post| %>
  <div class="post">
    <h2><%= link_to post.title, post %></h2>
    <p><%= truncate(post.content, length: 100) %></p>
  </div>
<% end %>
<%= link_to '検索に戻る', search_posts_path, class: 'btn btn-primary' %>

app/views/posts/toggle_like.js.erb
document.querySelector('.like-link').outerHTML = "<%= j(render 'like', post: @post) %>";

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>